name=DFRobot_GP8XXX
version=1.0.0
author=DFRobot
maintainer= fary<feng.yang@dfrobot.com>
sentence=GP8XXX 系列驱动库
paragraph=本库目前集成了 GP8503 GP8512 GP8101 GP8501 GP8211S GP8413 GP8403 GP8302 的驱动方法，用户使用本库就能很轻松的驱动这些模块
category=Sensors
url=https://github.com/DFRobot/DFRobot_GP8XXX
architectures=*