name=DFRobot_GP8XXX
version=1.0.0
author=DFRobot
maintainer= fary<feng.yang@dfrobot.com>
sentence=GP8XXX 系列驱动库
paragraph=sentence=GP8XXX 系列驱动库
category=Communication
url=https://github.com/DFRobot/DFRobot_GP8XXX
architectures=*